version = 0.1

[default.deploy.parameters]
stack_name = "roll-with-it"
resolve_s3 = false                  # does not create new bucket
s3_bucket = "roll-with-it-2025"
s3_prefix = "roll-with-it"
region = "us-east-1"
confirm_changeset = true            # asks for permission once shows you what's going to change
capabilities = "CAPABILITY_IAM"     # has ability to manipulate permissions (policies)
disable_rollback = true             # if deployment fails doesn't rollback (stays in failed state so you can check what went wrong)